### ISSUE TITLE
Anpassningsbar bild för \ftitlepage

### ISSUE THREAD

**Issue by antolu** [Fysiksektionen/latex-fstil#4]
Nya styrdokument som Stadgar och Reglemente, och senaste projektproppar/motioner har en fin bild på framsidan som inte är ett kugghjul på orange bakgrund. Borde implementeras så att man kan välja en bild för framsidan.

**Comment by gyback** [comment]
Jag har en lösning för det som utnyttjar predefined options från xargs.
Sen så är det en smakfråga på hur man vill centrera och välja storlek på de nya bilderna.
Den standard som vi använder i dagsläget(2\textwidth, left alignment) passar inte för heltäckande bilder då halva bilden kommer utanför papperet.

**Comment by eringh** [comment]
Tanken med den nuvarande va att vi en gång i tiden tyckte det såg snyggt ut (eventuellt passade det också med någon annan existerande grafisk profil eller mall för att göra saker).
Det går att ändra, men man kanske vill ha kvar det som default om man inte lägger in något annat specifikt.

**Comment by gyback** [comment]
Jag tyckte inte om att använda xargs så jag löste det på ett annat sätt som liknar lösningen vid motioner.

Tanken med att det finns ett default värde på den är att den ska fungera precis som innan om man inte specifierar en viss bild.

Anropet \ftitlepage funkar som vanligt och vill man ha en egen bild så skriver man \ftitlepage[BILD.EXT]

**Comment by gyback** [comment]
Jag har lagt till det i den senaste commit.
